group: 64x64
train:
  n_epochs: 100
  batch_size: 128
  lr: 1.0e-3
  KLD_weight: 0.1
  seed: 42

data:
  path_dir: ./images/
  image_size: 64
  n_channels: 3

net_arch:
  n_filters: 8
  n_layers: 5
  n_channels_latent: 92
