train:
  n_epochs: 10
  batch_size: 64
  lr: 1.0e-4
  KLD_weight: 0.5
  seed: 42

data:
  path_dir: ./images/
  image_size: 32
  n_channels: 3

net_arch:
  n_filters: 8
  n_layers: 4
  n_channels_latent: 24
